### ISSUE TITLE
`./bin/multisig.js` is outdated

### ISSUE THREAD

**Issue by braydonf** [bcoin-org/bsigner#18]
The current tool at `./bin/multisig.js` looks to be a CLI tool for interacting with bmultisig, however due to API changes the tool does not work, as the shape of the options has changed.

I propose this tool is moved to be a part of `bmultisig-cli` as mentioned at https://github.com/bcoin-org/bmultisig/issues/69

**Comment by braydonf** [comment]
The `--create-wallet` command does not work, and will give an error on the bmultisig side as:

```
[debug] (multisig) Error: map must be a object.
    at new Validator (bmultisig/node_modules/bval/lib/validator.js:25:13)
    at Route.handler (bmultisig/lib/http.js:314:27)
    at Router.handle (bmultisig/node_modules/bweb/lib/router.js:100:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async MultisigHTTP._handleStack (bmultisig/node_modules/bweb/lib/server.js:294:9)
    at async MultisigHTTP._handleRequest (bmultisig/node_modules/bweb/lib/server.js:203:9)
    at async HTTP._handleMounts (bmultisig/node_modules/bcoin/node_modules/bweb/lib/server.js:234:9)
    at async HTTP._handleRequest (bmultisig/node_modules/bcoin/node_modules/bweb/lib/server.js:198:9)
    at async Server.<anonymous> (bmultisig/node_modules/bcoin/node_modules/bweb/lib/server.js:126:9)
```

The command run was:
```
./bin/multisig.js --create-wallet --wallet=default --m 1 --n 1 --cosigner-name=tester --index=0 --vendor=trezor --network=regtest
```

After having both bcoin and bmultisig running:
```
bcoin --network=regtest --no-wallet
bmultisig --network=regtest
```
